import { cartAmount, type CartAmount } from "./src/cart";
const cart: CartAmount = cartAmount(123);
const cartKind: "cart" = cart.kind;
import { quoteAmount, type QuoteAmount } from "./src/quote";
const quote: QuoteAmount = quoteAmount(123);
const quoteKind: "quote" = quote.kind;
import { invoiceAmount, type InvoiceAmount } from "./src/invoice";
const invoice: InvoiceAmount = invoiceAmount(123);
const invoiceKind: "invoice" = invoice.kind;
import { paymentAmount, type PaymentAmount } from "./src/payment";
const payment: PaymentAmount = paymentAmount(123);
const paymentKind: "payment" = payment.kind;
import { refundAmount, type RefundAmount } from "./src/refund";
const refund: RefundAmount = refundAmount(123);
const refundKind: "refund" = refund.kind;
import { ledgerAmount, type LedgerAmount } from "./src/ledger";
const ledger: LedgerAmount = ledgerAmount(123);
const ledgerKind: "ledger" = ledger.kind;
const cartCents: number = cart.cents;
const cartFunction: (cents: number) => CartAmount = cartAmount;
const quoteCents: number = quote.cents;
const quoteFunction: (cents: number) => QuoteAmount = quoteAmount;
const invoiceCents: number = invoice.cents;
const invoiceFunction: (cents: number) => InvoiceAmount = invoiceAmount;
const paymentCents: number = payment.cents;
const paymentFunction: (cents: number) => PaymentAmount = paymentAmount;
const refundCents: number = refund.cents;
const refundFunction: (cents: number) => RefundAmount = refundAmount;
const ledgerCents: number = ledger.cents;
const ledgerFunction: (cents: number) => LedgerAmount = ledgerAmount;
